#!/bin/bash
# count the lines of the program

# echo "counting '"$1"'"
# find $1 | grep .*'.ml$' | grep -v main.ml | grep -v .*debug.*'.ml$' | xargs wc -l

echo $1

files=find ""$1 
#32.0    | grep -v 'main.ml'\
#    | grep -v .*debug.*'.ml$'
echo $files
cloc --by-file $files
